-- MySQL Script generated by MySQL Workbench
-- 06/01/17 12:02:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_sample
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_sample` ;

-- -----------------------------------------------------
-- Schema db_sample
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sample` DEFAULT CHARACTER SET utf8 ;
USE `db_sample` ;

-- -----------------------------------------------------
-- Table `db_sample`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_sample`.`customer` ;

CREATE TABLE IF NOT EXISTS `db_sample`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
