server:
  port: 6969

endpoints:
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST
swagger:
  configuration:
    properties:
    -
        name: LoanOrderInterface
        url: /api-doc/LoanOrderInterfaceV1.json
        version: 1.0
    -
        name: RealEstateInterface
        url: /api-doc/RealEstateInterfaceV1.0.json
        version: 1.0
    -
        name: LoanAdvisoryInterface
        url: /api-doc/LoanAdvisoryInterfaceV1.0.1.json
        version: 1.0.1
    -
        name: Client onboarding
        url: /api-doc/ClientOnboardingInterfaceV7.json
        version: 7.0
    -
        name: fil-bsa-axon-loan-advisory
        url: /api-doc/fil-bsa-axon-loan-advisory-0.0.8.yaml
        version: 0.0.8